export const fonts = {
  Black: 'Nunito-Black',
  BlackItalic: 'Nunito-BlackItalic',
  Bold: 'Nunito-Bold',
  BoldItalic: 'Nunito-BoldItalic',
  ExtraBold: 'Nunito-ExtraBold',
  ExtraBoldItalic: 'Nunito-ExtraBoldItalic',
  ExtraLight: 'Nunito-ExtraLight',
  ExtraLightItalic: 'Nunito-ExtraLightItalic',
  Italic: 'Nunito-Italic',
  Light: 'Nunito-Light',
  LightItalic: 'Nunito-LightItalic',
  Medium: 'Nunito-Medium',
  MediumItalic: 'Nunito-MediumItalic',
  Regular: 'Nunito-Regular',
  SemiBold: 'Nunito-SemiBold',
  SemiBoldItalic: 'Nunito-SemiBoldItalic',
};
